channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pip
  - notebook
  - pip:
    - azureml-defaults
    - azureml-widgets
    - azureml-train-core
    - azureml-pipeline
    - numpy
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - python-dotenv
    - joblib
    - tqdm
    - scikit-learn
    - scikit-surprise
    - pyodbc
    - SQLAlchemy
    - jupyter_contrib_nbextensions
    - python-dotenv