channels:
  - conda-forge
  - defaults
dependencies:
- python=3.8.8
- pip
- pip:
  - azureml-defaults
  - numpy
  - pandas
  - scipy
  - matplotlib
  - joblib
  - tqdm
  - scikit-learn
  - scikit-surprise