name: Test deploy function

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_WORKSPACE: ${{ secrets.AZURE_WORKSPACE }}
  PYTHON_VERSION: '3.8.8'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
      
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: 'Create function ressources'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.28.0
        inlineScript: |
          cd P9_03_function/
          ./function_create.sh
